[profile.release]
panic = 'unwind'

[workspace]
members = [
    'node',
    'pallets/*',
    'runtime',
]

[patch.crates-io]
frame-benchmarking = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-benchmarking-cli = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-executive = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-support = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-support-procedural = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-support-procedural-tools = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-support-procedural-tools-derive = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-system = { git = "https://github.com/paritytech/substrate.git", branch="master" }
frame-system-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-authorship = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-aura = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-babe = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-balances = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-bounties = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-collective = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-elections-phragmen = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-grandpa = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-indices = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-membership = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-multisig = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-offences = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-proxy = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-randomness-collective-flip = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-recovery = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-scheduler = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-session = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-staking = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-staking-reward-curve = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-sudo = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-timestamp = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-tips = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-transaction-payment = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-transaction-payment-rpc = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-treasury = { git = "https://github.com/paritytech/substrate.git", branch="master" }
pallet-utility = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-block-builder = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-basic-authorship = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-chain-spec = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-cli = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-client-api = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-client-db = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-babe-rpc = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-slots = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-manual-seal = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-consensus-epochs = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-executor = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-finality-grandpa-rpc = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-informant = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-keystore = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-network = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-offchain = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-rpc = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-service = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-telemetry = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-api = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-application-crypto = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-arithmetic = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-block-builder = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-blockchain = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-consensus = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-consensus-aura = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-consensus-babe = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-core = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-externalities = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-finality-grandpa = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-inherents = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-io = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-keystore = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-offchain = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-rpc = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-runtime = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-runtime-interface = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-state-machine = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-session = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-staking = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-std = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-storage = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-timestamp = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-tracing = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-transaction-pool = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-trie = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-version = { git = "https://github.com/paritytech/substrate.git", branch="master" }
substrate-frame-rpc-system = { git = "https://github.com/paritytech/substrate.git", branch="master" }
sp-runtime-interface-proc-macro = { git = "https://github.com/paritytech/substrate.git", branch="master" }