[package]
name = "node-template-runtime"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2018"
license = "Unlicense"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
static_assertions = "1.1.0"

frame-system = { version = "2.0.0", default-features = false }
frame-support = { version = "2.0.0", default-features = false }
frame-executive = { version = "2.0.0", default-features = false }
pallet-authorship = { version = "2.0.0", default-features = false }
pallet-balances = { version = "2.0.0", default-features = false }
pallet-collective = { version = "2.0.0", default-features = false }
pallet-membership = { version = "2.0.0", default-features = false }
pallet-elections-phragmen = { version = "3.0.0", default-features = false }
#pallet-aura = { version = "2.0.0", default-features = false }
pallet-babe = { version = "2.0.0", default-features = false }
pallet-grandpa = { version = "2.0.0", default-features = false }
pallet-indices = { version = "2.0.0", default-features = false }
#pallet-im-online = { version="2.0.0", default-features = false }
#pallet-multisig = { version = "2.0.0", default-features = false }
#pallet-offences = { version = "2.0.0", default-features = false }
#pallet-proxy = { version = "2.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "2.0.0", default-features = false }
#pallet-recovery = { version = "2.0.0", default-features = false }
#pallet-scheduler = { version = "2.0.0", default-features = false }
pallet-session = { version = "2.0.0", features = ["historical"], default-features = false }
pallet-staking = { version = "2.0.0", default-features = false }
pallet-staking-reward-curve = { version = "2.0.0", default-features = false }
pallet-sudo = { version = "2.0.0", default-features = false }
pallet-timestamp = { version = "2.0.0", default-features = false }
pallet-transaction-payment = { version = "2.0.0", default-features = false }
pallet-treasury = { version = "2.0.0", default-features = false }
pallet-utility = { version = "2.0.0", default-features = false }

serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false }
sp-block-builder = { default-features = false, version = "2.0.0"}
#sp-consensus-aura = { version = "0.8.0", default-features = false }
sp-consensus-babe = { version = "0.8.0", default-features = false }
sp-core = { version = "2.0.0", default-features = false }
sp-inherents = { default-features = false, version = "2.0.0"}
sp-offchain = { version = "2.0.0", default-features = false }
sp-runtime = { version = "2.0.0", default-features = false }
sp-session = { version = "2.0.0", default-features = false }
sp-staking = { version = "2.0.0", default-features = false }
sp-std = { version = "2.0.0", default-features = false }
sp-transaction-pool = { version = "2.0.0", default-features = false }
sp-version = { version = "2.0.0", default-features = false }

# Used for the node template's RPCs
frame-system-rpc-runtime-api = { version = "2.0.0", default-features = false }
pallet-transaction-payment-rpc-runtime-api = { version = "2.0.0", default-features = false }

# Used for runtime benchmarking
frame-benchmarking = { version = "2.0.0", default-features = false, optional = true }
frame-system-benchmarking = { version = "2.0.0", default-features = false, optional = true }
hex-literal = { version = "0.3.1", optional = true }

template = { version = "2.0.0", default-features = false, path = "../pallets/template", package = "pallet-template" }

[build-dependencies]
substrate-wasm-builder = { version = "3.0.0" }

[features]
default = ["std"]
std = [
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"pallet-balances/std",
	"pallet-babe/std",
	"pallet-grandpa/std",
	"pallet-collective/std",
	"pallet-elections-phragmen/std",
	"pallet-indices/std",
#	"pallet-im-online/std",
	"pallet-membership/std",
#	"pallet-multisig/std",
#	"pallet-proxy/std",
	"pallet-randomness-collective-flip/std",
#	"pallet-recovery/std",
#	"pallet-scheduler/std",
	"pallet-session/std",
	"pallet-staking/std",
	"pallet-sudo/std",
	"pallet-timestamp/std",
	"pallet-transaction-payment/std",
	"pallet-transaction-payment-rpc-runtime-api/std",
	"pallet-treasury/std",
	"pallet-utility/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-babe/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-staking/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"frame-system/std",
	"frame-system-rpc-runtime-api/std",
	"template/std",
]
runtime-benchmarks = [
	"sp-runtime/runtime-benchmarks",
	"frame-benchmarking",
	"frame-support/runtime-benchmarks",
	"frame-system-benchmarking",
	"hex-literal",
	"frame-system/runtime-benchmarks",
	"pallet-balances/runtime-benchmarks",
	"pallet-timestamp/runtime-benchmarks",
]
