[package]
name = "bp-traits"
version = "2.0.0"
authors = ["skyh24 <skyhighfeng@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
